select
	STATION_ID,
	STATION_NAME,
	STATION_LAT,
	STATION_LON,
	STATION_GEO,
	STATION_TYPE,
	STATION_CAPACITY,
	RENTAL_METHODS,
	REGION_NAME ,
	NHOOD_NAME ,
	BOROUGH_NAME,
	NHOOD_GEO
  from {{ source('STATIONS', 'STATIONS_RAW') }}